name: CI

on:
  push:
    branches: '*'
    tags: v*
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

env:
  MACOSX_DEPLOYMENT_TARGET: 10.12

defaults:
  run:
    shell: bash

jobs:
  test:
    name: ${{ matrix.arch }}-${{ matrix.data.os.target }}${{ matrix.data.os.version }} ${{ matrix.compiler }}
    runs-on: ${{ matrix.data.os.host }}
    continue-on-error: ${{ matrix.nightly == 'nightly' }}
    env:
      LIME_ARCH: ${{ matrix.arch }}
      LIME_COMPILER: ${{ matrix.compiler }}
      LIME_CROSS_COMPILE: ${{ matrix.data.cross_compile }}
      LIME_OS: ${{ matrix.data.os.target }}
      LIME_OS_VERSION: ${{ matrix.data.os.version }}
    strategy:
      fail-fast: false
      matrix:
        compiler: [ldc-latest]
        arch: [x86_64]
        data:
          - os:
              target: macos
              host: macOS-latest

          - os:
              target: linux
              host: ubuntu-latest

          - os:
              target: windows
              host: windows-latest

          - os:
              target: freebsd
              host: ubuntu-latest
              version: '14.0'
            cross_platform_actions: true
            cross_compile: true

          - os:
              target: openbsd
              host: ubuntu-latest
              version: '7.4'
            cross_platform_actions: true
            cross_compile: true

          - os:
              target: netbsd
              host: ubuntu-latest
              version: '10.0'
            cross_platform_actions: true
            cross_compile: true

        include:
          - data:
              os:
                target: linux
                host: ubuntu-latest
              cross_compile: true
              docker: true
            compiler: ldc-latest
            arch: arm64

          - data:
              os:
                target: linux
                host: ubuntu-latest
              cross_compile: true
              docker: true
            compiler: ldc-latest
            arch: ppc64le

          - data:
              os:
                target: linux
                host: ubuntu-latest
              cross_compile: true
              docker: true
            compiler: ldc-latest
            arch: riscv64

          - data:
              os:
                target: linux
                host: ubuntu-latest
            compiler: ldc-master
            arch: mips64el
            docker_arch: mips64le
            nightly: nightly

          - data:
              os:
                target: linux
                host: ubuntu-latest
              cross_compile: true
              docker: true
            compiler: ldc-latest
            arch: i386
            docker_arch: 386

          - data:
              os:
                target: windows
                host: windows-latest
            compiler: ldc-latest
            arch: i386

          - data:
              os:
                target: openbsd
                host: ubuntu-latest
                version: '7.4'
              cross_platform_actions: true
              cross_compile: true
            compiler: ldc-latest
            arch: arm64

          - data:
              os:
                target: linux
                host: ubuntu-latest
            compiler: ldc-beta
            arch: x86_64

          - data:
              os:
                target: linux
                host: ubuntu-latest
            compiler: ldc-master
            arch: x86_64
            nightly: nightly

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Test
        if: ${{ !matrix.data.cross_platform_actions && !matrix.data.docker }}
        run: ./.github/workflows/ci.sh

      - name: Build Tests
        if: ${{ matrix.data.cross_compile }}
        run: ./.github/workflows/build_tests.sh

      - name: Run Tests in VM
        if: ${{ matrix.data.cross_platform_actions }}
        uses: cross-platform-actions/action@v0.24.0
        with:
          shell: bash
          operating_system: ${{ matrix.data.os.target }}
          version: ${{ matrix.data.os.version }}
          environment_variables: LIME_CROSS_COMPILE
          run: ./.github/workflows/ci.sh

      - name: Set up QEMU
        if: ${{ matrix.data.docker }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ matrix.arch }}

      - name: Run Tests in Docker
        if: ${{ matrix.data.docker }}
        run: |
          docker run \
            --rm \
            -v $(pwd):/${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e LIME_CROSS_COMPILE=${{ env.LIME_CROSS_COMPILE }} \
            --platform linux/${{ matrix.docker_arch || matrix.arch }} \
            debian:unstable-slim \
            ./.github/workflows/ci.sh

      # - name: Debug
      #   if: ${{ failure() }}
      #   run: cat config/temp/mixin.d
