name: CI

on:
  push:
    branches: '*'
    tags: v*
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *

env:
  MACOSX_DEPLOYMENT_TARGET: 10.9

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test ${{ matrix.arch }}-${{ matrix.data.os.target }}${{ matrix.data.os.version }}
    runs-on: ${{ matrix.data.os.host }}
    continue-on-error: ${{ matrix.nightly == 'nightly' }}
    env:
      LIME_ARCH: ${{ matrix.arch }}
      LIME_COMPILER: ${{ matrix.compiler }}
      LIME_CROSS_COMPILE: ${{ matrix.data.cross_compile }}
      LIME_OS: ${{ matrix.data.os.target }}
      LIME_OS_VERSION: ${{ matrix.data.os.version }}
    strategy:
      matrix:
        compiler: [ldc-latest]
        arch: [x86_64]
        data:
          - os:
              target: macos
              host: macOS-latest

          - os:
              target: linux
              host: ubuntu-latest

          - os:
              target: windows
              host: windows-latest

          - os:
              target: freebsd
              host: macOS-latest
              version: 12.2
            cross_platform_actions: true
            cross_compile: true

          - os:
              target: openbsd
              host: macOS-latest
              version: 6.8
            cross_platform_actions: true
            cross_compile: true

        # include:
        #   - os:
        #       target: windows
        #       host: windows-latest
        #     compiler: ldc-latest
        #     arch: x86
        #
        #   - os:
        #       target: linux
        #       host: ubuntu-latest
        #     compiler: ldc-beta
        #     arch: x86_64
        #
        #   - os:
        #       target: linux
        #       host: ubuntu-latest
        #     compiler: ldc-master
        #     arch: x86_64
        #     nightly: nightly

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Test
        if: ${{ !matrix.data.cross_platform_actions }}
        run: ./.github/workflows/ci.sh

      - name: Build Tests
        if: ${{ matrix.data.cross_platform_actions }}
        run:
          ./.github/workflows/build_tests.sh

      - name: Run Tests
        if: ${{ matrix.data.cross_platform_actions }}
        uses: cross-platform-actions/action@v0.0.1
        with:
          shell: bash
          operating_system: ${{ matrix.data.os.target }}
          version: ${{ matrix.data.os.version }}
          environment_variables: LIME_CROSS_COMPILE
          run: ./.github/workflows/ci.sh

      - name: Debug
        if: ${{ failure() }}
        run: cat config/temp/mixin.d
